# Generated by Django 5.2.7 on 2025-10-27 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboration',
            options={'ordering': ['-collaboration_invitation__canva__updated_at', '-created_at'], 'verbose_name': 'Collaboration', 'verbose_name_plural': 'Collaborations'},
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='canva',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='collaboration_invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='api.collaborationinvitation'),
        ),
    ]
