# Generated by Django 5.2.7 on 2025-10-27 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_collaboration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='collaboration_invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='api.collaborationinvitation'),
        ),
    ]
