# Generated by Django 5.2.7 on 2025-10-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_collaboration_collaboration_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationinvitation',
            name='uuid',
        ),
    ]
